version: "3.4"
services:
  app:
    build:
      context: .
      target: base
    entrypoint: /go/bin/modd
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: mns_local
      POSTGRES_USER: mns_local
      POSTGRES_PASSWORD: localpass
